# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'


steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '**/*Tests*.csproj'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\Functions\'
    Contents: '**'
    TargetFolder: '$(BinStagingFolder)\$(Build.BuildId)'
    OverWrite: true
    flattenFolders: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(BinStagingFolder)\$(Build.BuildId)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(BinStagingFolder)\$(Build.BuildId)\Functions.zip'
    replaceExistingArchive: true

